name: PR to Master CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  ci:
    uses: ./.github/workflows/_ci.yml

  conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate conventional commits
        uses: wagoid/commitlint-action@v6
